[tests]
# Scripts that run unit tests (to be run before building debian, but after
# pre-requirements).  If it does not exist, or it is set to false, no script be
# executed.
unit = ["./test/utest"]

# Scripts that runs integration tests (to be run after building and installing
# debians).  If it does not exist, or it is set to false, no script be
# executed.
integration = []
